version: '3.1'

services:

#  db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: letsgomarco
#      MYSQL_DATABASE: somedatabase
#    ports:
#      - 3306:3306

  db:
    image: postgres:13.8
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
#      POSTGRES_DB: uat
    ports:
      - 5432:5432
#    command: ["postgres", "-c", "log_statement=all"]